services: 
  ftp:
    image: fauria/vsftpd
    container_name: vsftpd
    ports:
      - "21:21"
      - "21100-21115:21100-21115"
    environment:
      - FTP_USER=hailong
      - FTP_PASS=20225359
      - PASV_ADDRESS=127.0.0.1
      - PAST_MIN_PORT=21100
      - PAST_MAX_PORT=21115
      - LOG_STDOUT=1
    volumes:
      - ./ftpdata:/home/vsftpd